name: Run Bot Every Minute

on:
  schedule:
    - cron: "0 15-23 * * 1-5" # Run on weekdays from 8 AM to 4 PM Pacific Time
    - cron: "0 17-23,0-3 * * 6,0" # Run on weekends from 10 AM to 8 PM Pacific Time
  push:
    branches:
      - "main"

env:
  TZ: America/Los_Angeles

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run bot
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python bot.py
